### ISSUE TITLE
Urgent : Users are able to see other users notes.

### ISSUE THREAD

**Issue by akamath9** [ananthkamath/snote#4]
Update the index file to have if match on note.user_id == current_user[:id]

<p id="notice"><%= notice %></p>
<h1>Notes</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <% if note.user_id == current_user[:id] %>
      <tr>
          <td><%= note.title %></td>
          <td><%= note.body %></td>
          <td><%= note.user.email %></td>
          <td><%= link_to 'Show', note %></td>
          <td><%= link_to 'Edit', edit_note_path(note) %></td>
          <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Note', new_note_path %>

**Comment by ananthkamath** [comment]
Fixed.
